### PR TITLE
accept a list of placeIds, keep backwards compabtibility for passing …

### PR DESCRIPTION
**Pull request by franklintarter**
Here's an idea for your use case. Please take a look and let me know if you think this will work for you

@hartey11

### CODE REVIEW

**Comment by hartey11** [comment]
@franklintarter thanks! looks good. An array of ids makes sense to me!

**Comment by hartey11** [comment]
@franklintarter just updated and im getting the below error when I try gatsby develop

> TypeError: Cannot set property 'id' of undefined
    at resolvePlace (/Users/jonny/Projects/posh-wash/node_modules/gatsby-source-google-places/gatsby-node.js:13:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
    at async Object.exports.sourceNodes (/Users/jonny/Projects/posh-wash/node_modules/gatsby-source-google-places/gatsby-node.js:49:5)

**Comment by franklintarter** [comment]
@hartey11 
I can get a similar error if I downgrade my package back to 0.0.4 and try to run with the new `placeIds` config.

Can you please double-check that you're pulling the latest package? Blow away your node_modules and reinstall everything.
```bash
rm -rf node_modules
yarn # or pm install
```

If that doesn't work, can you paste your config (without API key) and package.json here? And I will take a look

**Comment by hartey11** [comment]
Reinstalling node modules did the trick! I'm seeing both places listed as nodes in GraphQL now. 

Thanks again for implementing this.

**Comment by hartey11** [comment]
Hey @franklintarter. I'm getting the same error when deploying to Netlify. I've tried "Clear cache and deploy site" which seems to install Yarn and dependencies again but the error persists!

Any idea how to get it to work on Netlify?

**Comment by hartey11** [comment]
@franklintarter actually looks like the issue is with gatsby build on my local version too. develop works fine though

**Comment by hartey11** [comment]
`const menus = require(`./gatsby/menus`);

module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
    menus,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    {
      resolve: `gatsby-plugin-react-redux`,
      options: {
        // [required] - path to your createStore module
        pathToCreateStoreModule: `./src/state/createStore`,
        // [optional] - options passed to `serialize-javascript`
        // info: https://github.com/yahoo/serialize-javascript#options
        // will be merged with these defaults:
        serialize: {
          space: 0,
          isJSON: true,
          unsafe: false,
        },
        // [optional] - if true will clean up after itself on the client, default:
        cleanupOnClient: true,
        // [optional] - name of key on `window` where serialized state will be stored, default:
        windowKey: "__PRELOADED_STATE__",
      },
    },
    {
      resolve: `gatsby-plugin-emotion`,
      options: {
        // Accepts all options defined by `babel-plugin-emotion` plugin.
      },
    },
    {
      resolve: `gatsby-source-google-places`,
      options: {
        placeIds: [
          "ChIJ8-0CIs4adkgRFAs5L2t2Q0k",
          "ChIJdda2YaENdkgRCwEXWRSTFyw",
        ],
        apiKey: "...", // TODO: API Key.
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
};
`

**Pull request merged**
